const actions = {
  INIT: "INIT",
  SHOW_AREA_SELECTOR: "SHOW_AREA_SELECTOR",
  LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
  GEOJSON_CLEAR: "GEOJSON_CLEAR",
  GEOJSON_FETCH_REQUEST: "GEOJSON_FETCH_REQUEST",
  GEOJSON_FETCH_SUCCEEDED: "GEOJSON_FETCH_SUCCEEDED",
  GEOJSON_FETCH_FAILED: "GEOJSON_FETCH_FAILED",
  GEOSTATISTICALDATA_FETCH_REQUEST : "GEOSTATISTICALDATA_FETCH_REQUEST",
  GEOSTATISTICALDATA_FETCH_SUCCEEDED : "GEOSTATISTICALDATA_FETCH_SUCCEEDED",
  GEOSTATISTICALDATA_FETCH_FAILED : "GEOSTATISTICALDATA_FETCH_FAILED"
}
export default actions
