const actions = {
  INIT: "INIT",
  LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
  AREA_CHANGE: "AREA_CHANGE",
  GEOJSON_CLEAR: "GEOJSON_CLEAR",
  GEOJSON_FETCH_REQUEST: "GEOJSON_FETCH_REQUEST",
  GEOJSON_FETCH_SUCCEEDED: "GEOJSON_FETCH_SUCCEEDED",
  GEOJSON_FETCH_FAILED: "GEOJSON_FETCH_FAILED",
  GEOSTATISTICALDATA_LOCAL_CHANGED : "GEOSTATISTICALDATA_LOCAL_CHANGED",
  GEOSTATISTICALDATA_LOCAL_FETCH_SUCEEDED : "GEOSTATISTICALDATA_LOCAL_FETCH_SUCEEDED",
  GEOSTATISTICALDATA_FETCH_REQUEST : "GEOSTATISTICALDATA_FETCH_REQUEST",
  GEOSTATISTICALDATA_FETCH_SUCCEEDED : "GEOSTATISTICALDATA_FETCH_SUCCEEDED",
  GEOSTATISTICALDATA_FETCH_FAILED : "GEOSTATISTICALDATA_FETCH_FAILED",
  GEOSTATISTICALDATA_CHANGE_COLUMN : "GEOSTATISTICALDATA_CHANGE_COLUMN",
  SPREADSHEET_OPEN:"SPREADSHEET_OPEN",
  SPREADSHEET_CLOSE:"SPREADSHEET_CLOSE"
}
export default actions
