const actions = {
  INIT: 'INIT',
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  HASH_UPDATE: 'HASH_UPDATE',
  AREA_CHANGE: 'AREA_CHANGE',
  GEOJSON_CLEAR: 'GEOJSON_CLEAR',
  GEOJSON_FETCH_REQUEST: 'GEOJSON_FETCH_REQUEST',
  GEOJSON_FETCH_SUCCEEDED: 'GEOJSON_FETCH_SUCCEEDED',
  GEOJSON_FETCH_FAILED: 'GEOJSON_FETCH_FAILED',
  GEOSTATISTICALDATA_LOCALFETCH_REQUEST:
    'GEOSTATISTICALDATA_LOCALFETCH_REQUEST',
  GEOSTATISTICALDATA_REMOTEFETCH_REQUEST:
    'GEOSTATISTICALDATA_REMOTEFETCH_REQUEST',
  GEOSTATISTICALDATA_FETCH_SUCCEEDED: 'GEOSTATISTICALDATA_FETCH_SUCCEEDED',
  GEOSTATISTICALDATA_FETCH_FAILED: 'GEOSTATISTICALDATA_FETCH_FAILED',
  GEOSTATISTICALDATA_CHANGE_COLUMN: 'GEOSTATISTICALDATA_CHANGE_COLUMN',
  SPREADSHEET_OPEN: 'SPREADSHEET_OPEN',
  SPREADSHEET_CLOSE: 'SPREADSHEET_CLOSE',
  EXAMPLEDATASETDEF_FETCH_SUCCEEDED: 'EXAMPLEDATASETDEF_FETCH_SUCCEEDED',
  EXAMPLESELECTOR_OPEN: 'EXAMPLESELECTOR_OPEN',
  EXAMPLESELECTOR_CLOSE: 'EXAMPLESELECTOR_CLOSE',
  EXAMPLEDATA_FETCH_REQUEST: 'EXAMPLEDATA_FETCH_REQUEST'
}
export default actions
