export const prefectureDef = [
  { "id" : "01", "prefecture_jp" : "北海道", "prefecture_en" : "hokkaido", scale : 5500 },
 { "id" : "02", "prefecture_jp" : "青森", "prefecture_en" : "aomori", scale : 18000 },
 { "id" : "03", "prefecture_jp" : "岩手", "prefecture_en" : "iwate", scale : 13000 },
 { "id" : "04", "prefecture_jp" : "宮城", "prefecture_en" : "miyagi", scale : 18673 },
 { "id" : "05", "prefecture_jp" : "秋田", "prefecture_en" : "akita", scale : 14033 },
 { "id" : "06", "prefecture_jp" : "山形", "prefecture_en" : "yamagata", scale : 15614 },
 { "id" : "07", "prefecture_jp" : "福島", "prefecture_en" : "fukushima", scale : 19426 },
 { "id" : "08", "prefecture_jp" : "茨城", "prefecture_en" : "ibaraki", scale : 19062
},
 { "id" : "09", "prefecture_jp" : "栃木", "prefecture_en" : "tochigi", scale : 24078 },
 { "id" : "10", "prefecture_jp" : "群馬", "prefecture_en" : "gumma", scale : 21428 },
 { "id" : "11", "prefecture_jp" : "埼玉", "prefecture_en" : "saitama", scale : 25000 },
 { "id" : "12", "prefecture_jp" : "千葉", "prefecture_en" : "chiba", scale : 19101 },
 { "id" : "13", "prefecture_jp" : "東京", "prefecture_en" : "tokyo", scale : 15000 },
 { "id" : "14", "prefecture_jp" : "神奈川", "prefecture_en" : "kanagawa", scale : 42165 },
 { "id" : "15", "prefecture_jp" : "新潟", "prefecture_en" : "niigata", scale : 12655 },
 { "id" : "16", "prefecture_jp" : "富山", "prefecture_en" : "toyama", scale : 32561 },
 { "id" : "17", "prefecture_jp" : "石川", "prefecture_en" : "ishikawa", scale : 12868 },
 { "id" : "18", "prefecture_jp" : "福井", "prefecture_en" : "fukui", scale : 24142 },
 { "id" : "19", "prefecture_jp" : "山梨", "prefecture_en" : "tamanashi", scale : 28593 },
 { "id" : "20", "prefecture_jp" : "長野", "prefecture_en" : "nagano", scale : 12551 },
 { "id" : "21", "prefecture_jp" : "岐阜", "prefecture_en" : "gifu", scale : 17263 },
 { "id" : "22", "prefecture_jp" : "静岡", "prefecture_en" : "shizuoka", scale : 21889 },
 { "id" : "23", "prefecture_jp" : "愛知", "prefecture_en" : "aichi", scale : 27150 },
 { "id" : "24", "prefecture_jp" : "三重", "prefecture_en" : "mie", scale : 14975 },
 { "id" : "25", "prefecture_jp" : "滋賀", "prefecture_en" : "shiga", scale : 25206 },
 { "id" : "26", "prefecture_jp" : "京都", "prefecture_en" : "kyoto", scale : 21428 },
 { "id" : "27", "prefecture_jp" : "大阪", "prefecture_en" : "osaka", scale : 29420 },
 { "id" : "28", "prefecture_jp" : "兵庫", "prefecture_en" : "hyogo", scale : 15123 },
 { "id" : "29", "prefecture_jp" : "奈良", "prefecture_en" : "nara", scale : 24931},
 { "id" : "30", "prefecture_jp" : "和歌山", "prefecture_en" : "wakayama", scale : 24205 },
 { "id" : "31", "prefecture_jp" : "鳥取", "prefecture_en" : "tottori", scale : 15000 },
 { "id" : "32", "prefecture_jp" : "島根", "prefecture_en" : "shimane", scale : 13000 },
 { "id" : "33", "prefecture_jp" : "岡山", "prefecture_en" : "okayama", scale : 21785 },
 { "id" : "34", "prefecture_jp" : "広島", "prefecture_en" : "hiroshima", scale : 21478 },
 { "id" : "35", "prefecture_jp" : "山口", "prefecture_en" : "yamaguchi", scale : 21180 },
 { "id" : "36", "prefecture_jp" : "徳島", "prefecture_en" : "tokushima", scale : 32217 },
 { "id" : "37", "prefecture_jp" : "香川", "prefecture_en" : "kagawa", scale : 41590 },
 { "id" : "38", "prefecture_jp" : "愛媛", "prefecture_en" : "ehime", scale : 16397 },
 { "id" : "39", "prefecture_jp" : "高知", "prefecture_en" : "kochi", scale : 19467 },
 { "id" : "40", "prefecture_jp" : "福岡", "prefecture_en" : "fukuoka", scale : 18373 },
 { "id" : "41", "prefecture_jp" : "佐賀", "prefecture_en" : "saga", scale : 34397 },
 { "id" : "42", "prefecture_jp" : "長崎", "prefecture_en" : "nagasaki", scale : 8448
},
 { "id" : "43", "prefecture_jp" : "熊本", "prefecture_en" : "kumamoto", scale : 20890 },
 { "id" : "44", "prefecture_jp" : "大分", "prefecture_en" : "oita", scale : 22426 },
 { "id" : "45", "prefecture_jp" : "宮崎", "prefecture_en" : "miyagawa", scale : 15560 },
 { "id" : "46", "prefecture_jp" : "鹿児島", "prefecture_en" : "kagoshima", scale : 8000 },
 { "id" : "47", "prefecture_jp" : "沖縄", "prefecture_en" : "okinawa", scale : 8000 },
];
